"""
validator.py
------------
Basically this step checks whether the XML we generated follows the formal
structure/requirements that real HLA labs use when submitting data.

citations:
https://schemas.nmdp.org/
https://www.sciencedirect.com/science/article/pii/S0198885915004346
https://schemas.nmdp.org/spec/hml/1.0.1/hml_1_0_1-example7-ngsFull.xml 

"""

import xmlschema      #external package used to validate XML files

class HMLValidator:
    def __init__(self, schema_path):
        self.schema_path = schema_path
        self.schema = xmlschema.XMLSchema(schema_path)

    def validate(self, file_path):
        """
        Validates the given .hml file against the HML schema.
        
        file_path: the XML/HML file generated by our program.

        xmlschema will raise an exception if:
            - The XML structure doesn't match the schema
            - Required elements are missing
            - Data types/formats don't match what the schema expects

        So we wrap the call in try/except to give user-friendly output instead
        of a scary stack trace.
        """
        try:
            self.schema.validate(file_path)
            print("[Validator] File is VALID")
            return True
        except Exception as e:
            print("[Validator] Validation FAILED")
            print(e)
            return False
